### ISSUE TITLE
I found mysterious codes in env/multiwoz.py

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#52]
Hi,
I found mysterious codes in env/multiwoz.py.

"reset" function in class MultiWozEnvironment,
https://github.com/ConvLab/ConvLab/blob/74cfda261babccc22038a1107033a38029636039/convlab/env/multiwoz.py#L91
self.history extends with f"{user_response}". 
So the result is, ['null', '$REAL_USER_RESPONSE']

but, when the episode progresses,
"step" function in class MultiWozEnvironment,
https://github.com/ConvLab/ConvLab/blob/74cfda261babccc22038a1107033a38029636039/convlab/env/multiwoz.py#L111
self.history extends with [f'sys_response', f'user_response']
So the result is, ['null', '$REAL_USER_RESPONSE', 'sys_response', 'user_response'...].

I guess the code's original intention is [f"{sys_response}", f"{user_response}"].
the expected result is, ['null', '$REAL_USER_RESPONSE', '$REAL_SYS_RESPONSE', '$REAL_USER_RESPONSE'].

Those codes affect MILU's 'parse' function. So, It might be important thing.

Please check this part and let us know.
Thank you!

**Comment by jeonggwanlee** [comment]
Those codes affect MILU's 'parse' function. So, It might be important thing.

**Comment by truthless11** [comment]
Fixed #53 . @jeonggwanlee Thanks for reporting the problem.

**Comment by jeonggwanlee** [comment]
Thanks!

**Comment by jeonggwanlee** [comment]
@truthless11, I saw your new commit but, it's still wrong, becayse there's no variable "sys_response" in this function.
I guess f'{sys_response'} should be modified into "action"

**Comment by truthless11** [comment]
@jeonggwanlee Done.

**Comment by jeonggwanlee** [comment]
@truthless11 Thank you!!
